//
//  CoursesModels.swift
//  Pearson
//
//  Created by Dima Tsurkan on 09.11.2017.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Courses {
    // MARK: Use cases
  
    enum FetchCourses {
        struct Request {
        }
        
        struct Response {
            var courses: [Course]
            var printableError: String?
        }
    
        struct ViewModel {
            var courses: [Course]
            var printableError: String?
        }
    }
}
