//
//  CoursesWorker.swift
//  Pearson
//
//  Created by Dima Tsurkan on 09.11.2017.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CoursesWorker {
    
    func fetchCourses(completion: @escaping ([Course]?, String?) -> Void) {
        pearsonAuthenticatedProvider.request(.myCourses) { (result) in
            do {
                let response = try result.dematerialize()
                let json = try JSONSerialization.jsonObject(with: response.data, options: [])
                if let array = json as? [[String: Any]] {
                    let courses = array.map { Course.parse(data: $0) }
                    completion(courses, nil)
                } else {
                    completion([], nil)
                }
            } catch {
                let printableError = error as CustomStringConvertible
                completion(nil, printableError as? String)
            }
        }
    }
}
