//
//  CoursesPresenter.swift
//  Pearson
//
//  Created by Dima Tsurkan on 09.11.2017.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CoursesPresentationLogic {
    func presentSomething(response: Courses.Something.Response)
}

class CoursesPresenter: CoursesPresentationLogic {
    weak var viewController: CoursesDisplayLogic?
  
    // MARK: Do something
  
    func presentSomething(response: Courses.Something.Response) {
        let viewModel = Courses.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
