//
//  AuthWorker.swift
//  Pearson
//
//  Created by Dima Tsurkan on 09.11.2017.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AuthWorker {
  
    func auth(login: String, password: String, completion: @escaping (String?, String?) -> Void) {
        pearsonProvider.request(.auth(login: login, password: password)) { (result) in
            do {
                let response = try result.dematerialize()
                let json = try JSONSerialization.jsonObject(with: response.data, options: []) as! [String : Any]
                let token = json["access_token"]
                UserDefaults.standard.set(token, forKey: XAppToken.DefaultsKeys.TokenKey.rawValue)
                completion(token as? String, nil)
            } catch {
                let printableError = error as CustomStringConvertible
                completion(nil, printableError as? String)
            }
        }
    }
}
