//
//  AuthViewController.swift
//  Pearson
//
//  Created by Dima Tsurkan on 09.11.2017.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthDisplayLogic: class {
    func displayError(viewModel: Auth.AuthProcess.ViewModel)
    func displayAuthentificatedUser(viewModel: Auth.AuthProcess.ViewModel)
}

class AuthViewController: UIViewController, AuthDisplayLogic {
    var interactor: AuthBusinessLogic?
    var router: (NSObjectProtocol & AuthRoutingLogic & AuthDataPassing)?
    
    // MARK: - Outlets
    
    @IBOutlet weak var loginTextField: UITextField!
    @IBOutlet weak var passwordTextField: UITextField!

    // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
  
    // MARK: Setup
  
    private func setup() {
        let viewController = self
        let interactor = AuthInteractor()
        let presenter = AuthPresenter()
        let router = AuthRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
  
  
    // MARK: View lifecycle
  
    override func viewDidLoad() {
        super.viewDidLoad()
        configureView()
    }
    
    // MARK: - AuthDisplayLogic
    
    func displayError(viewModel: Auth.AuthProcess.ViewModel) {
        showAlert(withTitle: "Auth Error", message: viewModel.printableError)
    }
    
    func displayAuthentificatedUser(viewModel: Auth.AuthProcess.ViewModel) {
        router?.routeToCources()
    }
  
    // MARK: - Internal
    
    private func configureView() {
        loginTextField.text = router?.dataStore?.login
        loginTextField.isUserInteractionEnabled = false
    }
    
    private func showAlert(withTitle title: String, message: String?) {
        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
        let okAction = UIAlertAction(title: "OK", style: .cancel, handler: nil)
        alertController.addAction(okAction)
        self.present(alertController, animated: true, completion: nil)
    }
    
    // MARK: - Actions
    
    @IBAction func loginButtonPressed(_ sender: Any) {
        if let text = passwordTextField.text, text.isEmpty {
            showAlert(withTitle: "Warning", message: "Password can't be empty")
            return
        }
        let request = Auth.AuthProcess.Request(login: "devdemo", password: "Secret12")
        interactor?.auth(request: request)
    }
}
