//
//  AuthPresenter.swift
//  Pearson
//
//  Created by Dima Tsurkan on 09.11.2017.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthPresentationLogic {
    func presentAuthentificaedUser(response: Auth.AuthProcess.Response)
    func presentError(response: Auth.AuthProcess.Response)
}

class AuthPresenter: AuthPresentationLogic {
    weak var viewController: AuthDisplayLogic?
  
    // MARK: - Auth
  
    func presentAuthentificaedUser(response: Auth.AuthProcess.Response) {
        let viewModel = Auth.AuthProcess.ViewModel(accessToken: response.accessToken, printableError: response.printableError)
        viewController?.displayAuthentificatedUser(viewModel: viewModel)
    }
    
    func presentError(response: Auth.AuthProcess.Response) {
        let viewModel = Auth.AuthProcess.ViewModel(accessToken: response.accessToken, printableError: response.printableError)
        viewController?.displayError(viewModel: viewModel)
    }
}
