//
//  AccountPresenter.swift
//  Pearson
//
//  Created by Dima Tsurkan on 09.11.2017.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountPresentationLogic {
    func presentSomething(response: Account.Something.Response)
}

class AccountPresenter: AccountPresentationLogic {
    weak var viewController: AccountDisplayLogic?
  
    // MARK: Do something
  
    func presentSomething(response: Account.Something.Response) {
        let viewModel = Account.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
