//
//  AccountInteractor.swift
//  Pearson
//
//  Created by Dima Tsurkan on 09.11.2017.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountBusinessLogic {
    func fetchProfile(request: Account.FetchProfile.Request)
}

protocol AccountDataStore {
    var user: User? { get set }
}

class AccountInteractor: AccountBusinessLogic, AccountDataStore {
    var presenter: AccountPresentationLogic?
    var worker: AccountWorker?
    var user: User?
  
    // MARK: - Fetch Profile
  
    func fetchProfile(request: Account.FetchProfile.Request) {
        worker = AccountWorker()
        worker?.fetchProfile(completion: { (user, error) in
            if let theUser = user {
                self.user = theUser
                let response = Account.FetchProfile.Response(user: self.user, printableError: nil)
                self.presenter?.presentUser(response: response)
            } else {
                let response = Account.FetchProfile.Response(user: nil, printableError: error)
                self.presenter?.presentError(response: response)
            }
        })
    }
}
