//
//  AccountPresenter.swift
//  Pearson
//
//  Created by Dima Tsurkan on 09.11.2017.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountPresentationLogic {
    func presentUser(response: Account.FetchProfile.Response)
    func presentError(response: Account.FetchProfile.Response)
}

class AccountPresenter: AccountPresentationLogic {
    weak var viewController: AccountDisplayLogic?
  
    // MARK: - Fethc User
    
    func presentUser(response: Account.FetchProfile.Response) {
        let viewModel = Account.FetchProfile.ViewModel(user: response.user, printableError: response.printableError)
        viewController?.displayUser(viewModel: viewModel)
    }
    
    func presentError(response: Account.FetchProfile.Response) {
        let viewModel = Account.FetchProfile.ViewModel(user: response.user, printableError: response.printableError)
        viewController?.displayError(viewModel: viewModel)
    }
  
}
