//
//  AccountInteractor.swift
//  Pearson
//
//  Created by Dima Tsurkan on 09.11.2017.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountBusinessLogic {
    func doSomething(request: Account.Something.Request)
}

protocol AccountDataStore {
    //var name: String { get set }
}

class AccountInteractor: AccountBusinessLogic, AccountDataStore {
    var presenter: AccountPresentationLogic?
    var worker: AccountWorker?
    //var name: String = ""
  
    // MARK: Do something
  
    func doSomething(request: Account.Something.Request) {
        worker = AccountWorker()
        worker?.doSomeWork()
    
        let response = Account.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
